//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MicroPCR.rc에서 사용되고 있습니다.
//
#define IDD_MICROPCR_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_REC_NOT_WORKING      132
#define IDB_BITMAP_REC_WORKING          133
#define IDD_PROGRESS_DIALOG             134
#define IDD_DIALOG_PID_MANAGER          135
#define IDD_DIALOG_PID_CREATE           136
#define IDD_DIALOG_SAVE                 137
#define IDD_DIALOG_TEMP_GRAPH           138
#define IDB_BITMAP_CY5                  151
#define IDB_BITMAP_FMA                  152
#define IDB_BITMAP_FAM                  152
#define IDB_BITMAP_HEX                  153
#define IDB_BITMAP_OFF                  154
#define IDB_BITMAP_ROX                  155
#define IDD_FORM_MAIN                   156
#define IDD_FORM_RESULT                 157
#define IDD_DIALOG_MAIN                 164
#define IDD_DIALOG_SETUP                166
#define IDD_DIALOG_PROTOCOL_EDITOR      168
#define IDD_DIALOG_PASSWORD             170
#define IDC_EDIT_DEVICE_STATUS          1000
#define IDC_EDIT_PCR_STATUS             1000
#define IDC_EDIT_CHAMBER_TEMP           1001
#define IDC_PROGRESS_CHAMBER_TEMP       1002
#define IDC_BUTTON_CONSTANTS            1003
#define IDC_BUTTON_GRAPHVIEW            1004
#define IDC_LIST_PCR_PROTOCOL           1005
#define IDC_BUTTON_PCR_START            1006
#define IDC_EDIT_MAGNETO_STATUS         1006
#define IDC_BUTTON_PCR_OPEN             1007
#define IDC_BUTTON_PCR_RECORD           1008
#define IDC_EDIT_MAX_ACTIONS            1009
#define IDC_EDIT_TIME_OUT               1010
#define IDC_EDIT_ARRIVAL_DELTA          1011
#define IDC_CUSTOM_PID_TABLE            1012
#define IDC_BUTTON_CONSTANTS_APPLY      1013
#define IDC_EDIT_LEFT_PROTOCOL_TIME     1014
#define IDC_EDIT_ELAPSED_TIME           1015
#define IDC_STATIC_PID_DEBUG            1016
#define IDC_EDIT_ARDUINO_STATUS         1016
#define IDC_EDIT_GRAPH_Y_MIN            1017
#define IDC_EDIT_Y_MAX                  1018
#define IDC_BUTTON1                     1019
#define IDC_BUTTON_BOOTLOADER           1019
#define IDC_BUTTON_FAN_CONTROL          1019
#define IDC_BUTTON_PID_NEW              1019
#define IDC_BUTTON_PID_CREATE_ADD       1019
#define IDC_BUTTON_CONNECT_MAGNETO      1019
#define IDC_BUTTON_START_PCR            1019
#define IDC_BUTTON_TEST                 1019
#define IDC_BUTTON_SAVE_CHANGES         1019
#define IDC_BUTTON_PROTOCOL_FILTER_FAM  1019
#define IDC_BUTTON_FILTER_FAM           1019
#define IDC_BUTTON_PASSWORD_OK          1019
#define IDC_PROGRESS_PROTOCOL           1020
#define IDC_EDIT_INTEGRAL_MAX           1020
#define IDC_BUTTON_SELECT               1020
#define IDC_BUTTON_PID_CREATE_COMPLETE  1020
#define IDC_BUTTON_PID_SELECT           1020
#define IDC_BUTTON_PROTOCOL_FILTER_HEX  1020
#define IDC_BUTTON_FILTER_HEX           1020
#define IDC_BUTTON_PASSWORD_CANCEL      1020
#define IDC_STATIC_PROGRESS             1021
#define IDC_BUTTON_ENTER_PID_MANAGER    1021
#define IDC_BUTTON_DELETE               1021
#define IDC_BUTTON_PID_CREATE_REMOVAL   1021
#define IDC_BUTTON_PID_DELETE           1021
#define IDC_EDIT_FL_RELATIVE_MAX        1021
#define IDC_BUTTON_PROTOCOL_FILTER_ROX  1021
#define IDC_BUTTON_FILTER_ROX           1021
#define IDC_BUTTON_LED_CONTROL          1022
#define IDC_EDIT_ARDUINO_MAGNET         1022
#define IDC_BUTTON_PROTOCOL_FILTER_CY5  1022
#define IDC_BUTTON_FILTER_CY5           1022
#define IDC_EDIT_CURRENT_P              1023
#define IDC_EDIT_ARDUINO_STATUS3        1023
#define IDC_EDIT_ARDUINO_TEMPER         1023
#define IDC_EDIT_CURRENT_I              1024
#define IDC_BUTTON_FAM                  1024
#define IDC_EDIT_CURRENT_D              1025
#define IDC_BUTTON_CONNECT_MAGNETO2     1026
#define IDC_CUSTOM_PID_TABLE2           1027
#define IDC_BUTTON_CONNECT_ARDUINO      1027
#define IDC_LIST_PID                    1028
#define IDC_BUTTON4                     1028
#define IDC_BUTTON_CONNECT_ARDUINO2     1028
#define IDC_BUTTON_SETUP                1028
#define IDC_EDIT_PID_START_TEMP         1029
#define IDC_BUTTON_CONNECT_ALARMRESET   1029
#define IDC_EDIT_PID_TARGET_TEMP2       1030
#define IDC_BUTTON_HEX                  1030
#define IDC_EDIT_PID_TARGET_TEMP3       1031
#define IDC_EDIT_PID_P                  1031
#define IDC_BUTTON_ROX                  1031
#define IDC_EDIT_PID_TARGET_TEMP4       1032
#define IDC_EDIT_PID_D                  1032
#define IDC_BUTTON_CY5                  1032
#define IDC_EDIT_PID_TARGET_TEMP5       1033
#define IDC_EDIT_PID_I                  1033
#define IDC_COMBO_PID_REMOVAL           1034
#define IDC_CUSTOM_PID_TABLE3           1035
#define IDC_EDIT1                       1036
#define IDC_EDIT_LOADED_PID             1036
#define IDC_EDIT_SAVE_LABEL             1036
#define IDC_EDIT_PCR_PROTC_NAME         1036
#define IDC_EDIT_CONNECTI_STATUS        1036
#define IDC_EDIT_MAX_CYCLES             1036
#define IDC_EDIT_PROTOCOL_NAME          1036
#define IDC_STATIC_SAVE_LABEL           1037
#define IDC_CHECK_TEMP_GRAPH            1039
#define IDC_EDIT_DISPLAY_DELTA          1039
#define IDC_EDIT_COMPENSATION           1040
#define IDC_EDIT2                       1041
#define IDC_EDIT_PHOTODIODE             1041
#define IDC_EDIT_CT_FAM                 1041
#define IDC_EDIT_PASSWORD_INPUT         1041
#define IDC_EDIT_FILTER_FAM             1041
#define IDC_COMBO_MAGNETO               1042
#define IDC_EDIT_CT_HEX                 1042
#define IDC_EDIT_FILTER_HEX             1042
#define IDC_COMBO_ARDUINO               1043
#define IDC_EDIT_CT_ROX                 1043
#define IDC_EDIT_FILTER_ROX             1043
#define IDC_EDIT_CT_CY5                 1044
#define IDC_EDIT_FILTER_CY5             1044
#define IDC_EDIT_Y_TARGET               1045
#define IDC_EDIT_FILTER_FAM_CT          1045
#define IDC_EDIT_Y_CURRENT              1046
#define IDC_EDIT_FILTER_HEX_CT          1046
#define IDC_EDIT_MAGNET_TARGET          1047
#define IDC_EDIT_FILTER_ROX_CT          1047
#define IDC_EDIT_MAGNET_CURRENT         1048
#define IDC_EDIT_FILTER_CY_CT           1048
#define IDC_EDIT_LOAD_TARGET            1049
#define IDC_EDIT_LOAD_CURRENT           1050
#define IDC_BUTTON_START                1052
#define IDC_PROGRESS_BAR                1053
#define IDC_CHECK_PROTOCOL_STOP         1055
#define IDC_CHECK_ACTION_STOP           1056
#define IDC_TREE_PROTOCOL               1057
#define IDC_STATIC_PROGRESSBAR          1058
#define IDC_STATIC_PROGRESSBAR2         1060
#define IDC_STATIC_PROGRESSBAR3         1061
#define IDC_STATIC_PROGRESSBAR4         1062
#define IDC_STATIC_PROGRESSBAR5         1063
#define IDC_STATIC_PROGRESSBAR6         1064
#define IDC_STATIC_PROGRESSBAR7         1065
#define IDC_STATIC_FAM                  1066
#define IDC_STATIC_HEX                  1067
#define IDC_STATIC_ROX                  1068
#define IDC_STATIC_CY5                  1069
#define IDC_BUTTON3                     1070
#define IDC_TAB                         1071
#define IDC_PROGRESS_PCR                1072
#define IDC_BUTTON_RESULT               1072
#define IDC_CHECK_TEMPERATURE           1076
#define IDC_PIC_LOGO                    1078
#define IDC_BUTTON2                     1080
#define IDC_BTN_FLTTEST                 1080
#define IDC_BUTTON_CONNECT              1080
#define IDC_RADIO1                      1081
#define IDC_BUTTON_EDIT_PROTOCOL        1081
#define IDC_RADIO_PROTOCOL_LABEL        1081
#define IDC_COMBO_DEVICE_LIST           1082
#define IDC_BUTTON_PROTOCOL_CANCEL      1082
#define IDC_STATIC_PROGRESS_STATUS      1083
#define IDC_RADIO_PROTOCOL_GOTO         1083
#define IDC_RADIO_PROTOCOL_SHOT         1084
#define IDC_PROGRESS_STATUS             1084
#define IDC_STATIC_PROGRESS_REMAINING_TIME 1085
#define IDC_COMBO_PROTOCOLS             1086
#define IDC_CUSTOM_PID_SETUP_TABLE      1087
#define IDC_LIST_PROTOCOL               1088
#define IDC_BUTTON_ADD_PROTOCOL         1089
#define IDC_BUTTON_PROTOCOL_SAVE        1091
#define IDC_CUSTOM_PROTOCOL_EDITOR      1092
#define IDC_EDIT_MAGNETO_PROTOCOL       1094

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
